import Head from 'next/head'
import Layout from '../../components/layout'
import { Col, Row } from 'antd'
import useTranslation from 'next-translate/useTranslation'
import styles from '../../styles/Events.module.scss'
import EventCard from '../../components/common/event-card'
import placeholderImg from '../../assets/images/doctors.jpeg'

const placeholderData = [
  {
    title: 'Event title Lorem ipsum dolor sit amet',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing el',
    date: '01.01.2022',
  },
  {
    title: 'Event title',
    // description:
    //   'Lorem ipsum dolor sit amet consectetur adipisicing elit dolor sit amet consectetur adipisicing elit dolor sit amet consectetur adipisicing elit',
    date: '01.01.2022',
  },
  {
    title: 'Event title',
    description:
      'dolor sit amet consectetur adipisicing elit dolor sit amet consectetur adis',
    date: '01.01.2022',
  },
  {
    title: 'Event title',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit dolor sit amet consectetur adipisicing elit dolor sit amet consectetur adipisicing elit',
    date: '01.01.2022',
  },
  {
    title: 'Event title',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit dolor sit amet consectetur adipisicing elit dolor sit amet consectetur adipisicing elit',
    date: '01.01.2022',
  },
  {
    title: 'Event title',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit dolor sit amet consectetur adipisicing elit dolor sit amet consectetur adipisicing elit',
    date: '01.01.2022',
  },
]

export default function Events() {
  const { t } = useTranslation('common')

  return (
    <div className={styles['events-wrapper']}>
      <Head>
        <title>{`Winmed - ${t('events.titleCase')}`}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>
        <div className={styles.container}>
          <h1>{t('events.titleCase')}</h1>
          <div className={styles['events-cards-wrapper']}>
            <Row gutter={32}>
              {placeholderData.map((item, index) => (
                <Col
                  span={8}
                  xs={{ span: 24 }}
                  md={{ span: 12 }}
                  lg={{ span: 8 }}
                  key={index}>
                  <EventCard
                    id={index}
                    image={placeholderImg}
                    date={item.date}
                    title={item.title}
                    description={item.description}
                  />
                </Col>
              ))}
            </Row>
            <button
              className={styles['btn-view-more']}
              // onClick={() => loadMoreEvents()}
            >
              {t('loadMoreProducts')}
            </button>
          </div>
        </div>
      </Layout>
    </div>
  )
}
