import Head from 'next/head'
import React from 'react'
import AboutSection from '../components/about-us'
import Carousel from '../components/carousel'
import Layout from '../components/layout'
import OurPartners from '../components/our-partners'
import OurProductsSection from '../components/our-products-section'
import ReferencesSection from '../components/references'
import styles from '../styles/Home.module.scss'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Winmed</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>
        <Carousel />
        <OurProductsSection />
        <AboutSection />
        <ReferencesSection />
        <OurPartners />
      </Layout>
    </div>
  )
}
