import React from 'react'
import Head from 'next/head'
import useTranslation from 'next-translate/useTranslation'
import Layout from '../../components/layout'
import styles from '../../styles/AboutUs.module.scss'
import ImageSection from '../../components/image-section'
import { AboutAttribute, aboutUsAttributes } from '../../constants/aboutUs'
import Image from 'next/image'
import ISOCertHospital from './../../assets/images/iso-cert-hospital.jpeg'
import DoctorsPresentation from './../../assets/images/doctors.jpeg'
import OurPartners from '../../components/our-partners'

export default function AboutUs() {
  const { t } = useTranslation('common')

  const renderAttributeItem = (attribute: AboutAttribute, index: number) => {
    return (
      <div key={index} className={styles['attribute-item']}>
        <div className={styles.icon}>
          <Image
            src={attribute.icon}
            alt={t(`${attribute.name}`)}
            width={20}
            height={28}
          />
        </div>
        <div className={styles.name}>
          <h5>{t(`${attribute.name}`)}</h5>
          <span>{t(`${attribute.description}`)}</span>
        </div>
      </div>
    )
  }

  const renderAboutAttributes = () => {
    return (
      <div className={styles['attributes-wrapper']}>
        {aboutUsAttributes.map((attrib: AboutAttribute, index: number) =>
          renderAttributeItem(attrib, index)
        )}
      </div>
    )
  }

  const renderYoutubeLink = () => {
    return (
      <div className={styles['link-card']}>
        <div className={styles.icon}>
          <Image
            src={'/icons/youtube-red.svg'}
            alt='youtube link'
            width={54}
            height={36}
          />
        </div>
        <span>{t(`followOnYoutube`)}</span>
      </div>
    )
  }

  return (
    <div className={styles['about-wrapper']}>
      <Head>
        <title>{`Winmed - ${t('aboutUs.titleCase')}`}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>
        <div className={styles.container}>
          <div className={styles['attributes-section']}>
            <ImageSection
              heading={t(`aboutUs.titleCase`)}
              content={t(`loremIpsumLong`)}
              buttonText=''
              staticImage={ISOCertHospital}
              hideButton
              reverse
              orderReverse>
              {renderAboutAttributes()}
            </ImageSection>
          </div>
          <div className={styles['video-section']}>
            <ImageSection
              heading=''
              content={t(`loremIpsumLong`)}
              buttonText=''
              staticImage={DoctorsPresentation}
              hideButton
              reverse={false}
              orderReverse={false}>
              {renderYoutubeLink()}
            </ImageSection>
          </div>
        </div>
        <div className={styles['partners-section']}>
          <OurPartners />
        </div>
      </Layout>
    </div>
  )
}
